# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\athar\src\qcore\qcore\gui\verse.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_verse(object):
    def setupUi(self, verse):
        verse.setObjectName("verse")
        verse.resize(500, 300)
        verse.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(verse)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verse_layout = QtWidgets.QVBoxLayout()
        self.verse_layout.setContentsMargins(10, 10, 10, 10)
        self.verse_layout.setSpacing(20)
        self.verse_layout.setObjectName("verse_layout")
        self.tabs = QtWidgets.QTabWidget(verse)
        self.tabs.setObjectName("tabs")
        self.verse_layout.addWidget(self.tabs)
        self.logbox = QtWidgets.QTextEdit(verse)
        self.logbox.setReadOnly(True)
        self.logbox.setObjectName("logbox")
        self.verse_layout.addWidget(self.logbox)
        self.verse_layout.setStretch(0, 3)
        self.verse_layout.setStretch(1, 2)
        self.verticalLayout.addLayout(self.verse_layout)

        self.retranslateUi(verse)
        self.tabs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(verse)

    def retranslateUi(self, verse):
        _translate = QtCore.QCoreApplication.translate
        verse.setWindowTitle(_translate("verse", "Verse"))
        self.logbox.setPlaceholderText(_translate("verse", "Message log"))
