# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verse.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_verse(object):
    def setupUi(self, verse):
        verse.setObjectName("verse")
        verse.setEnabled(True)
        verse.resize(800, 450)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(verse.sizePolicy().hasHeightForWidth())
        verse.setSizePolicy(sizePolicy)
        verse.setMinimumSize(QtCore.QSize(800, 450))
        self.horizontalLayout = QtWidgets.QHBoxLayout(verse)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verse_main_layout = QtWidgets.QVBoxLayout()
        self.verse_main_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verse_main_layout.setContentsMargins(10, 10, 10, 10)
        self.verse_main_layout.setSpacing(10)
        self.verse_main_layout.setObjectName("verse_main_layout")
        self.verse_tabs = QtWidgets.QTabWidget(verse)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verse_tabs.sizePolicy().hasHeightForWidth())
        self.verse_tabs.setSizePolicy(sizePolicy)
        self.verse_tabs.setTabBarAutoHide(False)
        self.verse_tabs.setObjectName("verse_tabs")
        self.server_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.server_tab.sizePolicy().hasHeightForWidth())
        self.server_tab.setSizePolicy(sizePolicy)
        self.server_tab.setObjectName("server_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.server_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.server_layout = QtWidgets.QVBoxLayout()
        self.server_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.server_layout.setObjectName("server_layout")
        self.select_instruments_layout = QtWidgets.QHBoxLayout()
        self.select_instruments_layout.setContentsMargins(5, 5, 5, 5)
        self.select_instruments_layout.setSpacing(20)
        self.select_instruments_layout.setObjectName("select_instruments_layout")
        self.instrument_type_layout = QtWidgets.QHBoxLayout()
        self.instrument_type_layout.setObjectName("instrument_type_layout")
        self.instrument_type_label = QtWidgets.QLabel(self.server_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.instrument_type_label.sizePolicy().hasHeightForWidth()
        )
        self.instrument_type_label.setSizePolicy(sizePolicy)
        self.instrument_type_label.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.instrument_type_label.setObjectName("instrument_type_label")
        self.instrument_type_layout.addWidget(self.instrument_type_label)
        self.instrument_type_choices = QtWidgets.QComboBox(self.server_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.instrument_type_choices.sizePolicy().hasHeightForWidth()
        )
        self.instrument_type_choices.setSizePolicy(sizePolicy)
        self.instrument_type_choices.setEditable(False)
        self.instrument_type_choices.setCurrentText("")
        self.instrument_type_choices.setPlaceholderText("")
        self.instrument_type_choices.setObjectName("instrument_type_choices")
        self.instrument_type_layout.addWidget(self.instrument_type_choices)
        self.instrument_type_layout.setStretch(0, 1)
        self.instrument_type_layout.setStretch(1, 3)
        self.select_instruments_layout.addLayout(self.instrument_type_layout)
        self.instrument_id_layout = QtWidgets.QHBoxLayout()
        self.instrument_id_layout.setObjectName("instrument_id_layout")
        self.instrumentIdLabel = QtWidgets.QLabel(self.server_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.instrumentIdLabel.sizePolicy().hasHeightForWidth()
        )
        self.instrumentIdLabel.setSizePolicy(sizePolicy)
        self.instrumentIdLabel.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.instrumentIdLabel.setObjectName("instrumentIdLabel")
        self.instrument_id_layout.addWidget(self.instrumentIdLabel)
        self.instrument_id_choices = QtWidgets.QComboBox(self.server_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.instrument_id_choices.sizePolicy().hasHeightForWidth()
        )
        self.instrument_id_choices.setSizePolicy(sizePolicy)
        self.instrument_id_choices.setPlaceholderText("")
        self.instrument_id_choices.setObjectName("instrument_id_choices")
        self.instrument_id_layout.addWidget(self.instrument_id_choices)
        self.instrument_id_layout.setStretch(0, 1)
        self.instrument_id_layout.setStretch(1, 3)
        self.select_instruments_layout.addLayout(self.instrument_id_layout)
        self.select_instruments_button_layout = QtWidgets.QHBoxLayout()
        self.select_instruments_button_layout.setContentsMargins(-1, 0, -1, -1)
        self.select_instruments_button_layout.setObjectName(
            "select_instruments_button_layout"
        )
        self.add_button = QtWidgets.QPushButton(self.server_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_button.sizePolicy().hasHeightForWidth())
        self.add_button.setSizePolicy(sizePolicy)
        self.add_button.setObjectName("add_button")
        self.select_instruments_button_layout.addWidget(self.add_button)
        self.remove_button = QtWidgets.QPushButton(self.server_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.remove_button.sizePolicy().hasHeightForWidth()
        )
        self.remove_button.setSizePolicy(sizePolicy)
        self.remove_button.setObjectName("remove_button")
        self.select_instruments_button_layout.addWidget(self.remove_button)
        self.select_instruments_button_layout.setStretch(0, 1)
        self.select_instruments_button_layout.setStretch(1, 1)
        self.select_instruments_layout.addLayout(self.select_instruments_button_layout)
        self.select_instruments_layout.setStretch(0, 2)
        self.select_instruments_layout.setStretch(1, 2)
        self.select_instruments_layout.setStretch(2, 1)
        self.server_layout.addLayout(self.select_instruments_layout)
        self.instruments_list = QtWidgets.QListWidget(self.server_tab)
        self.instruments_list.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers
        )
        self.instruments_list.setSelectionMode(
            QtWidgets.QAbstractItemView.MultiSelection
        )
        self.instruments_list.setObjectName("instruments_list")
        self.server_layout.addWidget(self.instruments_list)
        self.connect_instruments_layout = QtWidgets.QHBoxLayout()
        self.connect_instruments_layout.setContentsMargins(50, 5, 50, 5)
        self.connect_instruments_layout.setSpacing(100)
        self.connect_instruments_layout.setObjectName("connect_instruments_layout")
        self.setup_button = QtWidgets.QPushButton(self.server_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setup_button.sizePolicy().hasHeightForWidth())
        self.setup_button.setSizePolicy(sizePolicy)
        self.setup_button.setObjectName("setup_button")
        self.connect_instruments_layout.addWidget(self.setup_button)
        self.serve_button = QtWidgets.QPushButton(self.server_tab)
        self.serve_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serve_button.sizePolicy().hasHeightForWidth())
        self.serve_button.setSizePolicy(sizePolicy)
        self.serve_button.setObjectName("serve_button")
        self.connect_instruments_layout.addWidget(self.serve_button)
        self.teardown_button = QtWidgets.QPushButton(self.server_tab)
        self.teardown_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.teardown_button.sizePolicy().hasHeightForWidth()
        )
        self.teardown_button.setSizePolicy(sizePolicy)
        self.teardown_button.setObjectName("teardown_button")
        self.connect_instruments_layout.addWidget(self.teardown_button)
        self.connect_instruments_layout.setStretch(0, 1)
        self.connect_instruments_layout.setStretch(1, 1)
        self.connect_instruments_layout.setStretch(2, 1)
        self.server_layout.addLayout(self.connect_instruments_layout)
        self.verticalLayout.addLayout(self.server_layout)
        self.verse_tabs.addTab(self.server_tab, "")
        self.verse_main_layout.addWidget(self.verse_tabs)
        self.logbox = QtWidgets.QTextEdit(verse)
        self.logbox.setReadOnly(True)
        self.logbox.setObjectName("logbox")
        self.verse_main_layout.addWidget(self.logbox)
        self.verse_main_layout.setStretch(0, 3)
        self.verse_main_layout.setStretch(1, 2)
        self.horizontalLayout.addLayout(self.verse_main_layout)

        self.retranslateUi(verse)
        self.verse_tabs.setCurrentIndex(0)
        self.instrument_type_choices.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(verse)

    def retranslateUi(self, verse):
        _translate = QtCore.QCoreApplication.translate
        verse.setWindowTitle(_translate("verse", "Verse"))
        self.instrument_type_label.setText(_translate("verse", "Instrument type"))
        self.instrumentIdLabel.setText(_translate("verse", "Instrument ID"))
        self.add_button.setText(_translate("verse", "Add"))
        self.remove_button.setText(_translate("verse", "Remove"))
        self.setup_button.setText(_translate("verse", "Setup"))
        self.serve_button.setText(_translate("verse", "Serve"))
        self.teardown_button.setText(_translate("verse", "Teardown"))
        self.verse_tabs.setTabText(
            self.verse_tabs.indexOf(self.server_tab), _translate("verse", "Server")
        )
        self.logbox.setPlaceholderText(_translate("verse", "Message log"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    verse = QtWidgets.QWidget()
    ui = Ui_verse()
    ui.setupUi(verse)
    verse.show()
    sys.exit(app.exec_())
